server:
  port: 2003

spring:
  application:
    name: seata-account-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/seata_account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Kingback666
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    alibaba:
      seata:
        tx-service-group: billion_tx_group

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.billion.springcloud.domain

management:
  endpoints:
    web:
      exposure:
        include: '*'
