server:
  port: 9572

spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      discovery:
        locator:
#          开启动态创建路由的功能，利用微服务名进行路由
          enabled: true
      routes:
      - id: paymentport
#        uri: http://localhost:8001 静态路由
        uri: lb://CLOUD-PAYMENT-SERVICE
#        断言，共有9中常用断言
        predicates:
        - Path=/payment/port
        - After=2021-04-30T13:37:05.792+08:00[Asia/Shanghai]
#        - Cookie=uname,\w+
#        - Header=myrequestheader,\d+
#        - Host=**.baidu.com
        - Method=GET
        - Query=uname,\w+
        filters:
#        - AddRequestParameter=name,value

      - id: paymentget
#        uri: http://localhost:8002 静态路由方式
#        动态路由方式，lb指springcloud协议
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/get/**

      - id: paymentcreate
#        uri: http://localhost:8002 静态路由
        uri: lb://CLOUD-PAYMENT-SERVICE
        predicates:
        - Path=/payment/create/**


eureka:
  client:
    # 是否向注册中心注册本服务：默认为true为是。false注册中心不需要将自己注册进去
    register-with-eureka: true
    # 是否从注册中心抓取己有注册信息，默认为true
    # 单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: gateway9572
    prefer-ip-address: true
    #向服务器端发送心跳间隔
    lease-renewal-interval-in-seconds: 30
    #服务器端等待心跳时间上限
    lease-expiration-duration-in-seconds: 90


