server:
  port: 8801

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 自定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        output: # 这个名字是一个自定义通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          contentType: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置


eureka:
  client:
    # 是否向注册中心注册本服务：默认为true为是。false注册中心不需要将自己注册进去
    register-with-eureka: true
    # 是否从注册中心抓取己有注册信息，默认为true
    # 单节点无所谓，集群必须为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: stream-provider8801
    prefer-ip-address: true
    #向服务器端发送心跳间隔
    lease-renewal-interval-in-seconds: 30
    #服务器端等待心跳时间上限
    lease-expiration-duration-in-seconds: 90


