server:
  port: 9003

spring:
  application:
    name: cloudalibaba-payment-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
