server:
  port: 80

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/payment?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Kingback666

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.billion.entity