server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名字
  client:
    # 是否向注册中心注册本服务：true为是。false注册中心不需要将自己注册进去
    register-with-eureka: false
    # false表示自己是注册中心，职责是维护服务实例，并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址,多个时用逗号隔开
      defaultZone: http://eureka7002.com:7002/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/(单机版）
  server:
    #自我保护模式，默认开启
    enable-self-preservation: true
    #指定时间内没有检测到心跳则剔出微服务
    #eviction-interval-timer-in-ms: 0